### ISSUE TITLE
Possible to start Dashboard with sidebar toggle off

### ISSUE THREAD

**Issue by andrewvmail** [zksailor534/react-adminlte-dash#1]
Just wondering if it's possible to initially start sidebar off when using Dashboard component?

Thanks for the awesome component.

A

**Comment by zksailor534** [comment]
It isn't currently possible unless you decouple Header and Sidebar from the Dashboard component, but it looks like a very small change to make it work.  I'll make that change as soon as I get the chance.

**Comment by andrewvmail** [comment]
Awesome thanks!!
