### ISSUE TITLE
Possible to insert a footer?

### ISSUE THREAD

**Issue by andrewvmail** [zksailor534/react-adminlte-dash#3]
Hi there again just wondering if there is a away to embedded a footer at the same level as the header. I tried to insert a footer in between Dashboard tags and its inserting it one level down...

Thanks in advance

**Comment by zksailor534** [comment]
This seems like a good project for a snow day like today.  Look for it in v0.4.0.

**Comment by andrewvmail** [comment]
Wow that was fast.
Thank you, your the best!
A
