### ISSUE TITLE
font-awesome icon and title not shown on navbar Header.Item

### ISSUE THREAD

**Issue by andrewvmail** [zksailor534/react-adminlte-dash#6]
Any clue on why icon and title is not shown ? The link is working correctly though. Using latest.

```
const nav = (d) => ([
  <Header.Item href={ `https://github.com/a/a` }
    iconClass="fa fa-calculator"
    key="1"
    title="Github" />,
  <Header.UserMenu name="User" signOutAction={ () => d(logout()) } key="2" />,
]);
```

also noticing footerChildren={ <span>Footer</span> } is not outputting footer. Everything else is rendering fine. 

<img width="1209" alt="developer_tools_-_http___localhost_3500_calculator_and_lift_debt_solutions_and_index_js_ _lift-app" src="https://cloud.githubusercontent.com/assets/2431354/24832991/ce805cec-1c71-11e7-8880-a5c1671b4acb.png">

**Comment by zksailor534** [comment]
Hi, sorry it took me so long to get back to you.  I just had a chance to drop your navbar into my demo page and it worked just fine there.  Unfortunately, I can't come up with anything that might be causing your problem.  If you want to provide me with more info or a larger sample, I might be able to figure out more.
![image](https://cloud.githubusercontent.com/assets/460162/25065934/9cbd9c54-21e6-11e7-82fb-ad54167ad09d.png)
